Support pre-20.03 Nixpkgs
mozilla/nixpkgs-mozilla pull request #234
Opened 2020-07-30 23:04 UTC by matthewbauer

toRustTarget was added in https://github.com/nixos/nixpkgs/commits/83ac9c07e4df352e177ebdf978320089a137183a

So not all nixpkgs have it. We can provide a backup of it in this
case.

Fixes #232

2020-08-10 00:00 UTC, lf- requested changes
`undefined variable 'lib' at /nix/store/3spd0g7vp1n81ccnydfrvqackfpgbajc-nixpkgs-mozilla-src/rust-overlay.nix:83:48`

2020-08-10 00:00 UTC, lf- commented on rust-overlay.nix
> +    or "${cpu_}-${vendor.name}-${kernel.name}${lib.optionalString (abi.name != "unknown") "-${abi.name}"}");
this needs to be `super.lib.optionalString`, not `lib.optionalString`

2020-08-10 00:02 UTC, lf- commented
This isn't quite right. See 3ae360a.

2020-08-18 15:22 UTC, matthewbauer commented
> This isn't quite right. I have committed a tested and working fix in [3ae360a](https://github.com/mozilla/nixpkgs-mozilla/commit/3ae360a339edd23aa7d51c9a56ac10880f1c5179).

Thanks!

2020-08-18 19:42 UTC, lf- approved these changes

2021-04-16 10:09 UTC, eugeneia commented
I’d appreciate this landing since I’m running into this. Any chance? :-)

2021-07-29 10:08 UTC, nbp commented on rust-overlay.nix
> +    }.${cpu.name} or platform.rustc.arch or cpu.name;
Q: Any reason to add `platform.rustc.arch` as opposed to what is [currently implemented in Nixpkgs](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/compilers/rust/default.nix#L33-L42)

2026-07-13 11:35 UTC, closed without merging