Add rust platform compatible with nixpkgs rust platform
mozilla/nixpkgs-mozilla pull request #241
Opened 2020-09-16 15:47 UTC by asdf8dfafjk

This change adds a rust platform that can be directly used to compile rust applications from nixpkgs. e.g. rust-analyzer would be installed as 

```
	rust-analyzer = nixpkgs.rust-analyzer.override{ 
		unwrapped = (
			nixpkgs.rust-analyzer-unwrapped.override
			{
				rustPlatform = ( nixpkgs.rustPlatformOf ( nixpkgs.rustChannelOf rustVersion ) );
;
				cargoSha256 = "15kjcgxmigm0lwbp8p0kdxax86ldjqq9q8ysj6khfhqd0173184n";
			}
		);
	};
```

I tested this using the following `shell.nix`-

```
{
	nixpkgs_tarball ? 
		fetchTarball
		{
			url = https://github.com/NixOS/nixpkgs/archive/ef1fd9d0fb64f80aedcd77be6733d7a8c858dba8.tar.gz;
			sha256 = "14knhkvllzqqwls70j5kjxkm6ia3mxmjcwh2fwn3phvx6s910i2a";
		}
	, 
	rustVersion? { date = "2020-08-07"; channel = "nightly" ; },
}: 

# https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks/rust.section.md
let 
	moz_overlay = import (
		/home/zx/workspace/git/nixpkgs-mozilla
	);

	nixpkgs  = ( 
		import 
			nixpkgs_tarball
			{
				overlays = [ moz_overlay ];
			} 
	);
	# extraBuildInputs = ( builtins.map ( ebis: nixpkgs.${ebis} ) extraBuildInputStrings );
	rustExtensions =
		[ 
			"rust-src" 
		]
	;

	mozilla_rust_platform = ( nixpkgs.rustPlatformOf ( nixpkgs.rustChannelOf rustVersion ) );

	rust-analyzer = nixpkgs.rust-analyzer.override{ 
		unwrapped = (
			nixpkgs.rust-analyzer-unwrapped.override
			{
				rustPlatform = mozilla_rust_platform;
				cargoSha256 = "15kjcgxmigm0lwbp8p0kdxax86ldjqq9q8ysj6khfhqd0173184n";
			}
		);
	};
in
		nixpkgs.stdenv.mkDerivation {
				name = "blah";
				buildInputs = [ rust-analyzer ];
		} 

```

I did two tests with two different versions of nightlies and in `nix show-derivation` of respective derivations, rust source's date was as expected. Let me know if you need me to make any changes.

2020-09-29 10:21 UTC, nbp reviewed
This looks good apart from the style which does not match the surrounding code.
I will merge it later, once the style is fixed.

2020-09-30 08:57 UTC, asdf8dfafjk commented on rust-overlay.nix
> +    ;
Thanks for including this. And thank you very much for the lifesaver overlay. 

I've made the suggested changes

2020-09-30 17:52 UTC, nbp requested changes

2020-09-30 17:52 UTC, nbp commented on rust-overlay.nix
> +  };
These 2 attributes are part of the let-in, add one indentation level to these attributes.

2021-02-27 14:36 UTC, closed without merging