initial flake support
mozilla/nixpkgs-mozilla pull request #248
Opened 2021-01-15 08:42 UTC by garbas

resurrect #217

2021-06-03 13:40 UTC, nbp requested changes
From what I understand flakes are all about pinning to a specific version.
The overlays defined in nixpkgs-mozilla repository are mostly about getting the latest versions of every package, even with a pin-ed version of nixpkgs-mozilla.

So what is the point of pinning nixpkgs-mozilla with a flake if this overlay is not deterministic?

2021-06-03 13:40 UTC, nbp commented on flake.lock
> +      },
Sorry if I fail to understand all the principles of flakes, but I do not understand why `nixpkgs-mozilla` should have a `flake.lock` in the repository. `nixpkgs-mozilla` is meant to work with all versions, and as such locking to a specific one would add more pain to the users of these overlays, no?

Would this have to be updated at every update of `nixos-unstable` channel?
Shouldn't this lock be defined in external projects which are relying on `nixpkgs-mozilla` instead?

2021-06-03 13:40 UTC, nbp commented on flake.nix
> +            )
While I understand that this will define `rust = import ./rust-overlay.nix;` this deserve a comment, such that people can easily understand how to use it.

2021-07-12 15:39 UTC, mohe2015 commented on flake.lock
> +      },
You can do `nixpkgs-mozilla.inputs.nixpkgs.follows = "nixpkgs";` to override this but yes if it doesn't fail without this file (which would need to be tested) - this is probably not needed.

2021-07-12 15:41 UTC, mohe2015 commented
@garbas If you find the time please adress the requested changes. Would love to get this merged.

2021-07-12 15:43 UTC, closed without merging

2021-07-12 15:53 UTC, mohe2015 commented
@garbas why did you close?