Allow optional installation of rust-docs component
mozilla/nixpkgs-mozilla pull request #253
Opened 2021-03-14 13:10 UTC by cpcloud

This PR allows opting out of installing the `rust-docs`
component.

It can be used (for example) as follows, to create :

```nix
let
  tarballPath = https://github.com/cpcloud/nixpkgs-mozilla/archive/install-docs-optional.tar.gz;
  moz_overlay = import (builtins.fetchTarball tarballPath);
  pkgs = import <nixpkgs> { overlays = [ moz_overlay ]; };
in
pkgs.mkShell {
  name = "rust-shell-no-rust-docs";
  buildInputs = [
    (pkgs.rustChannelOf {
      channel = "beta";
      installDoc = false;
    })
  ];
}
```

Closes #252.

2021-03-28 16:07 UTC, miangraham commented
I'm vendoring cpcloud's fork because it makes my CI builds stop crying due to unnecessary doc installation adding 10 minutes or so to each run. Wish I had more upvotes to give. Please merge.

2021-03-28 18:06 UTC, cpcloud commented
@miangraham You may want to look into using [`fenix`](https://github.com/nix-community/fenix). I've been using it in https://github.com/cpcloud/turbocheck, and I'm liking it quite a bit.

2021-08-03 13:15 UTC, nbp requested changes
Thanks, this change looks good except for the fact we should parametrize `installDoc` at the package level instead of the manifest file. (see comment below)

Also, I think most users of this overlay are likely feeling the same burden. Thus making the documentation copy default to false would be a good idea.

2021-08-03 13:15 UTC, nbp commented on rust-overlay.nix
> +  fromManifestFile = manifest: { stdenv, fetchurl, patchelf, installDoc }:
note: `installDoc` has no reason to bubble up to the processing of the Manifest file. A few lines below, there is `makeOverridable ({extensions, targets, targetExtensions}: …)` which is use to wrap each package in a similar way as `callPackage` which makes it usable with `rust.override { extensions = ["rust-src"]; }`.

This would be the place where to add `installDoc ? false`, such that it can be enabled by user who wants the doc to be installed.

2021-09-05 13:00 UTC, cpcloud commented
@nbp I believe I have addressed your comments.

2021-09-13 13:16 UTC, nbp requested changes
Thanks for making these modifications, but I presume you might have noticed some issues or forgot to commit all changes.

2021-09-13 13:16 UTC, nbp commented on rust-overlay.nix
> +    };
This revert a change from a previous patch which should cause this patch to not work as expected.

2021-09-13 13:16 UTC, nbp commented on rust-overlay.nix
>          stdenv.mkDerivation {
nit: There is no need to add `installDoc` as argument of `installComponent` (no `s`), as it would be captured like `stdenv` is.

2021-12-20 17:47 UTC, closed without merging