firefox-overlay: add specifying binary name
mozilla/nixpkgs-mozilla pull request #289
Opened 2022-03-22 03:26 UTC by Artturin

will be needed once
https://github.com/NixOS/nixpkgs/pull/165161
is merged

(none of these will be needed on at least master after that)

2022-03-26 14:35 UTC, K900 commented
Probably want to reconcile this with https://github.com/mozilla/nixpkgs-mozilla/pull/284 somehow too.

2022-03-28 19:41 UTC, andersk requested changes

2022-03-28 19:41 UTC, andersk commented on firefox-overlay.nix
> +      // super.lib.optionalAttrs (super.firefox-unwrapped ? binaryName) { binaryName = "firefox"; };
This doesn’t work. The parameter is still called `applicationName`; it’s just now passed through as `binaryName`, breaking the previous detection.

2022-04-01 02:44 UTC, colemickens commented
If I understand correctly, I need this to merge to unblock `flake-firefox-nightly`. Until this is merged, users of my overlay are stranded on an old nightly.

2022-04-01 03:11 UTC, andersk requested changes

2022-04-01 03:11 UTC, andersk commented on firefox-overlay.nix
> +    })) { };
This doesn’t work on nixos-21.11 (the current stable branch).

```console
$ nix build --no-link -Lf ~/nixpkgs latest.firefox-bin
firefox-release-bin-unwrapped> cannot find executable file `/nix/store/7w1mvq57pk7zr0zj51rb03gpp5rihb17-firefox-release-bin-unwrapped-98.0.2/bin/firefox-release-bin-unwrapped'
error: builder for '/nix/store/w9k2z5g4qym7zpbh69ks0h69avmii6cp-firefox-release-bin-unwrapped-98.0.2.drv' failed with exit code 1;
       last 1 log lines:
       > cannot find executable file `/nix/store/7w1mvq57pk7zr0zj51rb03gpp5rihb17-firefox-release-bin-unwrapped-98.0.2/bin/firefox-release-bin-unwrapped'
       For full logs, run 'nix log /nix/store/w9k2z5g4qym7zpbh69ks0h69avmii6cp-firefox-release-bin-unwrapped-98.0.2.drv'.
```

2022-04-06 18:45 UTC, closed without merging

2022-04-06 18:48 UTC, Artturin commented on firefox-overlay.nix
> +    })) { };
lets revisit this when 21.11 is eol