Restore SYSROOT detection for Darwin
mozilla/nixpkgs-mozilla pull request #309
Opened 2023-04-25 23:01 UTC by ggreif

2023-06-26 09:28 UTC, nbp commented
> Bump for attention.

Unfortunately, this does not work this way …
You can always ping me on https://matrix.to/#/#mozilla:nixos.org .

2023-06-26 09:33 UTC, nbp commented on rust-overlay.nix
> +              cp --remove-destination $RUSTC_DRIVER_PATH $out/lib/
Shouldn't this file be copied before the loop which is using conditionally checking whether this file exists before using patchelf?

2023-07-28 16:18 UTC, ggreif commented
Looks like #304 has fixed this, so closing for now.

2023-07-31 20:57 UTC, Artturin requested changes
There's `stdenv.hostPlatform.extensions.sharedLibrary` so no need for duplication

2023-08-11 10:29 UTC, ggreif commented
@Artturin @nbp This is now a very mild delta, any chance to review?

2023-08-11 15:34 UTC, Artturin approved these changes
I don't use this overlay nor can I merge but the code looks ok.

2026-07-13 11:35 UTC, closed without merging